apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.application.appName }}
  labels:
    name: {{ .Values.application.appName }}
    role: agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.application.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.application.appName }}
    spec: 
      hostname: {{ .Values.application.appName }}
      hostNetwork: false
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: {{ .Values.application.appName }}
        image: {{ .Values.application.image }}:{{ .Values.application.imageVersion }}
        env:
        - name: HAMOCK_INFER
          value: "true"
        - name: HAMOCK_OPENAI_MODEL
          value: {{ .Values.configuration.model }}
        - name: HAMOCK_OPENAI_URL
          value: http://{{ .Values.configuration.nameGuest }}:{{ .Values.configuration.portGuest }}
        {{- if .Values.configuration.urlLog }}
        - name: HAMMOCK_DOWNLOAD_URL
          value: {{ .Values.configuration.urlLog }}
        {{- end }}
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
      terminationGracePeriodSeconds: 30
